### ISSUE TITLE
How to use this with React?

### ISSUE THREAD

**Issue by maxkahnt** [propjockey/aug-compile#1] opened 2020-10-30 23:18 UTC
I am not sure where to put the `augCompileAll()` call and if a generic react app meets the necessary requirements at all.

I managed to invoke the command by explicitly copying the script to my react app's public folder, including
`<script src="%PUBLIC_URL%/aug-compile-global.js"></script>` in `public/index.html`'s head, and calling `<script type="text/javascript">augCompileAll();</script>` between the closing tags for body and html. Inspecting the elements, I can see that the compile process has been somewhat successful: I have `data-augmented-ui-complied` attributes with additional paramaters like `compile-x` but my html's head then contains an empty `<style data-aug-compile-styles=""></style>` and the entire augmentation is lost :-|

**Comment by JaneOri** [comment] 2020-11-01 18:36
Hi @maxkahnt 

My guess is that your components are not rendered when you're calling augCompileAll since you do it synchronously at the bottom of your markup, so you may be able to fix the problem just by calling `augCompileAll()` in the same place you do now, just by using a setTimout:
```js
setTimeout(augCompileAll, 1000)
```

If that doesn't fix your issue, this probably wouldn't work well with React as-is anyway unless you were only compiling augmented-ui designs onto static wrappers or uncontrolled react components https://reactjs.org/docs/uncontrolled-components.html since React wants to control the rendered view and augCompile changes DOM

...a react wrapper component could be made to handle the state it creates like other libraries have done to work with React though... might be an interesting thing for me to add (or someone to create)

Anyway, please let me know either way and we'll figure out a path forward for you.
// James

PS: the style tag will be empty because the compiled styles are added by CCSOM, so you'll have to access the styles with javascript to see them

**Comment by maxkahnt** [comment] 2020-11-01 23:21
It seems like the background is not correctly set on the `after` pseudo element. If I manually add it to the CSS inspector, everything appears to be looking normal again.

(I will use this knowledge to simultaneously approach https://github.com/propjockey/augmented-ui/issues/11 without regrets :-) )

Below you can still see the iterations of my comment :)

----

With the `setTimeout` I can actually watch the augmentation disappear after a second, nice ;).

~~Had me thinking what I expected this module to do at all and I am concerned that I might have completely missed its point. I assumed it would get rid of the CSS-var evaluation overhead, i.e. I thought it _precompiled_ the clip-path polygons assembly that is the chaining of all your `--aug-xxx` and application of the Space Toggles. If that is not correct, then... sorry.~~
Upon further inspection I can now see that all the variables vanish from the element inspector and that the `clip-path` becomes static.

I am not sure if I understand the terms in your "static wrappers" paragraph correctly; the (un)controlled components notation seems to refer to forms only which is not my concern. I am not sure what to report in response to that in order to advance the issue.

~~I trust you on that the compiled styles might just not be directly inspectable, though I find it surprising that the dynamically modified DOM is. Since the header style tag and the compiled class names are added and the clip-path's are computed, I still feel like it might just be that `insertRule` fails since I cannot even see the static ones that you declare in lines 14 to 38 in `aug-compile-global.js`.~~
It is not inspectable in the DOM, but I think I can actually see all the styles in the Rules inspector.

**Comment by JaneOri** [comment] 2020-11-02 07:14
Hm. That sounds like a bug but the bg should be copied over to the compiled styles in any case:
https://github.com/propjockey/aug-compile/blob/main/aug-compile-es6.js#L72
It works in my testing...

I might not know an edge case about `getPropertyValue` because my understanding is that no matter how you're setting the background for the ::after pseudo, it shouldn't matter since it's copying the computed style...

Are you setting it in CSS yourself instead of using `--aug-border-bg` on the element?
If yes, are you using `background` or are you using a more specific `background-color` or similar?

Any chance you can reproduce it in a jsbin or codepen or a public repo so I can take a closer look?

**Comment by maxkahnt** [comment] 2020-11-02 08:14
Yep, here is a codepen example extending your setup from my augmented-ui issue: https://codepen.io/maxkahnt/pen/wvWjmmR
Actually, it works in chromium, but fails in firefox (81.0), so it probably is a bug or just unsupported in this version although I could not find any corresponding issue by a quick google search.

For completeness, let me answer your other questions although they might be irrelevant with the observation above: In my use-case I set the background using `--aug-border-bg`, the behaviour also occurs if I have no custom css vars and use the defaults, though.

**Comment by JaneOri** [comment] 2020-11-02 10:40
Hey @maxkahnt thank you very much for the report and demo

I've published a fix: https://www.npmjs.com/package/aug-compile

Please update and let me know if you're good to go now or if there's anything else!

**Comment by maxkahnt** [comment] 2020-11-02 11:03
Yep, works for me Thanks!

**Comment by maxkahnt** [comment] 2020-11-02 12:18
Sorry, but this seems to break delegated-border. I think you are quicker to set up an example than I am, but I will do it, if the description does not suffice.
With your latest proposition in https://github.com/propjockey/augmented-ui/issues/11 I might no longer need to delegate anyway ;)

PS: Would you prefer having another issue? The title certainly no longer is appropriate.

**Comment by maxkahnt** [comment] 2020-11-02 21:39
Find below my react component that does what I want. It still has some quirks, but I'm happy to share my results here (jsx files cannot be attached, so i'm copy pasting the entire code) that come off the fruitful discussion with you, @James0x57, here and in https://github.com/propjockey/augmented-ui/issues/11.

React component
---
```
import React, { useEffect, useRef } from 'react';
import { makeStyles } from '@material-ui/core/styles';
import { augCompileEl } from 'aug-compile/aug-compile-es6';
// import 'augmented-ui/augmented-ui.min.css';
// import './augmented-ui.min.css';


const useStyles = makeStyles({
  container: {
    position: 'relative',
  },
  sibling: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    top: 0,
    left: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
  },
  glow: {
    filter: 'drop-shadow(0 0 2px white) drop-shadow(0 0 4px skyblue)',
  },
  augborder: {
    '--aug-border-all': '1px',
    '--aug-border-bg': 'white',
    width: '100%',
    height: '100%',
  },
  bordermod: x => x.border,
  inlaymod: x => x.inlay,
});

const set0 = pos => {
  return {
    border: { [`--aug-border-${pos}`]: '0px' },
    inlay: { [`--aug-inlay-${pos}`]: '0px' },
  };
};

export default function Augment({ clipping, children, noborder, inlaystyle }) {
  const cls = useStyles(set0(noborder));
  const borderRef = useRef();
  const inlayRef = useRef();
  useEffect(() => {
    augCompileEl(inlayRef.current);
    augCompileEl(borderRef.current);
    const borderCS = getComputedStyle(borderRef.current, '::after');
    const borderClip = borderCS.getPropertyValue('clip-path');
    borderRef.current.parentNode.style.clipPath = borderClip;
  }, []);

  return (
    <div className={`${cls.container}`}>
      <div className={`${cls.glow} ${cls.sibling}`}>
        <div
          ref={borderRef}
          data-augmented-ui={`${clipping} border compile`}
          className={`${cls.bordermod} ${cls.augborder}`}
        />
      </div>
      <div
        ref={inlayRef}
        data-augmented-ui={`${clipping} inlay compile`}
        className={`${cls.inlaymod}`}
        style={inlaystyle}
      >
        {children}
      </div>
    </div>
  );
}
```
Quick doc
---
The component wraps any `children` in an augmentation defined by `clipping` with 1px white border and outward glow.
I added a custom variable `noborder` that can be set to top, bottom, right, or left and has essentially disappear the border on that side (I use it for elements that stick to the viewport boundary).
The elements are compiled on component mount (and the inward shadow gets clipped dynamically).
**Note**: As of now the shadow is only visible if the `augmented-ui.min.css` is manually modified. (Replace all "-1px" by "-Rpx" and "+1 px" by "+ Rpx". Spaces matter! R is some value greater than the drop shadow blur radius. R=4 in the component above. This is why I include it from a local copy instead of the generic module. See https://github.com/propjockey/augmented-ui/issues/11#issuecomment-720367707.) Furthermore, due to some bug in postcss I cannot run a proper build with react if the CSS is imported here, see e.g. https://github.com/jessmear/fcc-quote-machine/pull/1#issue-319039593, hence I do include the CSS file via my `index.html` still. (Apparently this could be circumvented by introducing more intermediate variables to reduce the nestedness, but I really don't want to alter the augmented-ui library all that much.)

Aug-compile in React
---
By now I think that the above shows the correct way to apply `aug-compile` in React without additional overhead (issue title is viable again, yay!). It is also way easier to implement and maintain than the `augCompileAll` solution in `index.html` that I used before. I am not sure about the actual performance impact yet, though. I might report back. Maybe server side rendering is key to actual gains here (though I do not know precisely what that means and implies really, as of now, to be honest).

Quirks
---
The component splits up the border and inlay to deal with the outward shadow clipping. As a result the inlay interior is no longer covered by the border stack. It behaves slightly different than an augmented-ui element rendered with `both`. In particular, an element set to full width within the inlay covers the space that should only be occupied by the border (and the border-inlay-gap). This might be an artifact of separating border and inlay, at least I would expect the inlay clipping to be strictly _within_ the boundary clipping region. I assume that it has something to do with the usage of the pseudo elements in the `both` case which does not generalize well to splitting up `border` and `inlay`, or it is an oversight for historic reasons, or I am totally wrong... :-)
This however is the reason why I have an additional parameter `inlaystyle` above. It allows to clip a full size image with a visually conforming result. Here is my custom react component for that use case:
```
import React from 'react';
import Augment from './Augment';

export default function ClippedImage({ src, width, alt }) {
  const bg = `url("${src}") 0 0 / auto 100% no-repeat`;
  return (
    <div style={{ width: width }}>
      <Augment
        clipping="tl-clip tr-clip bl-2-clip-x br-clip"
        inlaystyle={{ '--aug-inlay-bg': bg }}
      >
        <img src={src} alt={alt} style={{ width: '100%', opacity: 0 }} />
      </Augment>
    </div>
  );
}
```
I'm happy about any input for improvement.

**Comment by JaneOri** [comment] 2020-11-03 00:35
Ah, yeah, you're right, delegate elements aren't considered for aug-compile... I need to fix that. I didn't even document the delegates in v1 so I've gotta change my baseline and respect that people may be using them now.

I really appreciate how much you're diving into augmented-ui btw - it's fun to talk about the deeper parts for the first time haha 

Two things that may help:
1. In your useEffect if you use my replace between borderClip -> filterClip from the function here: https://github.com/propjockey/augmented-ui/issues/11#issuecomment-720419873
then you can avoid modifying the library if you want to. It's a safe regex replace that won't have a false positive because that pattern only occurs in that one spot since it's the only time the path loops counter clockwise anywhere in augmented-ui.

2. In order for the separate inlay to respect the border when they're split up, you'll have to manually add the --aug-border-[pos] values to the --aug-inlay-[pos] values. Inlay does not consider any of the border values unless the border is enabled.
You _could_ just add `both` on the inlay instead and give the border a transparent bg, but it's already pretty heavy so that's a trade off for your consideration

Anyway, sounds like you're good to go now? Need anything else? I can't wait to see what you're working on! :)

---

I'm going to leave this open until I can add delegate support, hopefully this weekend

**Comment by JaneOri** [comment] 2020-11-09 07:24
![augcompile](https://user-images.githubusercontent.com/7545075/98511303-220a4000-222a-11eb-8e96-4f44f65b1288.gif)

Working on the release right now, added some tests including an animation one to demonstrate the gains 👍

**Comment by JaneOri** [comment] 2020-11-09 07:34
Published: https://www.npmjs.com/package/aug-compile
Delegates work automatically now

Closing issue (but please feel free to discuss here or in new issues if you run into anything)

(note: it's v2.0.0 since there were major changes so you may have to update your package.json to upgrade)

**Closed as completed by JaneOri** 2020-11-09 07:34 UTC

**Comment by maxkahnt** [comment] 2020-11-09 15:50
Awesome!

I decided to also remove the `data-augmented-ui-reset` as I do not use `data-augmented-ui` outside of this component.
Maybe it is worth considering to add this to `augCompileAll`? (It obviously has no place in augCompileEl.)

Many thanks!

For anybody aiming for something similar, find below my (current)

React component
--- 
```
import React, { useEffect, useRef } from 'react';
import { makeStyles } from '@material-ui/core/styles';
import { augCompileEl } from 'aug-compile/aug-compile-es6';
import 'augmented-ui/augmented-ui.min.css';

const useStyles = makeStyles({
  container: {
    position: 'relative',
    clipPath: 'none',
  },
  sibling: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    top: 0,
    left: 0,
  },
  content: {
    position: 'relative',
  },
  glow: {
    filter: 'drop-shadow(0 0 2px white) drop-shadow(0 0 4px skyblue)',
  },
  augborder: {
    '--aug-border-all': '1px',
    '--aug-border-bg': 'white',
    width: '100%',
    height: '100%',
  },
  auginlay: {
    '--aug-inlay-all': '3px',
  },
  bordermod: x => x.border,
  inlaymod: x => x.inlay,
});

const set0 = pos => {
  return {
    border: { [`--aug-border-${pos}`]: '0px' },
    inlay: { [`--aug-inlay-${pos}`]: '0px' },
  };
};

export default function Augment({
  className = '',
  clipping,
  clipClass = '',
  children,
  noborder = undefined,
}) {
  const cls = useStyles(set0(noborder));
  const containerRef = useRef();
  const borderRef = useRef();
  useEffect(() => {
    augCompileEl(containerRef.current);
    augCompileEl(borderRef.current);
    const borderCS = getComputedStyle(borderRef.current, '::after');
    const borderClip = borderCS.getPropertyValue('clip-path');
    const outerSize = '10px';
    const filteredClip = borderClip.replace(
      /-1px ([^,]+,)\s*-1px(?: calc[^,]*,){3} -1px -1px,\s+-1px/,
      (_, tlBorderIn) => {
        return `-${outerSize} ${tlBorderIn} -${outerSize} calc(100% + ${outerSize}), calc(100% + ${outerSize}) calc(100% + ${outerSize}), calc(100% + ${outerSize}) -${outerSize}, -${outerSize} -${outerSize}, -${outerSize}`;
      }
    );
    borderRef.current.parentNode.style.clipPath = filteredClip;
    borderRef.current.parentNode.removeAttribute('data-augmented-ui-reset');
  }, []);

  return (
    <div
      ref={containerRef}
      className={`${className} ${cls.inlaymod} ${clipClass} ${cls.container}`}
      data-augmented-ui={`${clipping} delegated-inlay compile`}
    >
      <div className={`${cls.glow} ${cls.sibling}`} data-augmented-ui-reset>
        <div
          ref={borderRef}
          data-augmented-ui={`${clipping} border compile`}
          className={`${cls.bordermod} ${clipClass} ${cls.augborder}`}
        />
      </div>
      <div data-augmented-ui-inlay className={`${cls.auginlay} ${cls.content}`}>
        {children}
      </div>
    </div>
  );
}
```
